### PR TITLE
Re-rendered for py36 build using conda-smithy 2.4.5

### PR DESCRIPTION
**Pull request by PertuyF**
Build number has been increased as version is still 0.7.1

### CODE REVIEW

**Comment by PertuyF** [comment]
To anyone who will look toward merging this PR: Please note that the appveyor build failed only for Miniconda35, and that the error is a 502 BadGateway on `https://conda.anaconda.org/conda-forge/noarch/repodata.json`.
As the link is working, it was likely a temporary error at the time of the build.
I am new with all this though, and I don't know how to rerun the check.

**Comment by kwilcox** [comment]
@conda-forge-admin, please add noarch: python

**Comment by kwilcox** [comment]
This should be good to go... build bump shouldn't be needed since its a `noarch` package now.

**Comment by PertuyF** [comment]
@conda-forge-admin could anyone consider merging this PR please?

**Comment by xhochy** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
Superseded by https://github.com/conda-forge/sphinx-autobuild-feedstock/pull/5

**Pull request closed without merging**
